=== Jedzia/BackBock/Jedzia.BackBock.Model/Data/BackupData.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2011 rel. 2 (http://www.altova.com) by Venom (ICO) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="BackupData">
        <xs:complexType>
            <xs:sequence minOccurs="0" maxOccurs="unbounded">
                <xs:element name="BackupItem" type="BackupItem" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="Name" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="BackupItem">
        <xs:attribute name="Name" type="xs:string" use="required"/>
        <xs:attribute name="IsEnabled" type="xs:boolean" default="false"/>
        <xs:attribute name="Test"/>
        <xs:attribute name="IsInterface" type="xs:boolean"/>
    </xs:complexType>
    <xs:complexType name="PathData">
        <xs:sequence>
            <xs:element name="Exclusion" type="Wildcard" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="Inclusion" type="Wildcard" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="Path" type="xs:string" use="required"/>
        <xs:attribute name="Wildcard" type="xs:string" use="optional"/>
    </xs:complexType>
    <xs:complexType name="Wildcard">
        <xs:attribute name="Pattern" type="xs:string" use="required"/>
        <xs:attribute name="Enabled" type="xs:boolean" default="false"/>
    </xs:complexType>
</xs:schema>

=== Jedzia/BackBock/Jedzia.BackBock.Model/Data/BackupData01.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2011 rel. 2 (http://www.altova.com)-->
<BackupData Name="String" xsi:noNamespaceSchemaLocation="file:///D:/E/Projects/CSharp/BackBock/Jedzia.BackBock.Model/Data/BackupData.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<BackupItem IsEnabled="false" Name="Firefox" Test="text"/>
	<BackupItem IsInterface="true" Name="Meine Texte" IsEnabled="true" Test="text"/>
	<BackupItem IsInterface="true" Name="D:\ misc" IsEnabled="true" Test="text"/>
	<BackupItem IsInterface="true" Name="String" IsEnabled="true" Test="text"/>
	<BackupItem IsInterface="true" Name="String" IsEnabled="true" Test="text"/>
	<BackupItem IsInterface="true" Name="Blabllaah" IsEnabled="false" Test="text"/>
	<BackupItem IsInterface="true" Name="Music" IsEnabled="true" Test="text"/>
	<BackupItem IsInterface="true" Name="Thunderbird Data" IsEnabled="true" Test="text"/>
	<BackupItem IsInterface="true" Name="Password-Safe" IsEnabled="true" Test="text"/>
</BackupData>
