=== Jedzia/BackBock/Jedzia.BackBock.Model/Data/ClassDataItem.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2011 rel. 2 (http://www.altova.com) by Venom (ICO) -->
<!--W3C Schema generated by XMLSpy v2011 rel. 2 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="ClassDataItem">
    <xs:annotation>
      <xs:documentation>Contains the DTO layer for class diagram data.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:attribute name="ItemType" type="xs:string" use="required"/>
      <xs:attribute name="Name" type="xs:string" use="required"/>
      <xs:attribute name="Color" type="xs:string" use="required"/>
      <xs:attribute name="Scope" type="xs:string"/>
      <xs:attribute name="AccessSpecifier" type="xs:string" />
      <xs:attribute name="Static" type="xs:boolean" default="false"/>
      <xs:attribute name="Signature" type="xs:string"/>
      <xs:attribute name="Parameternames" type="xs:string"/>
      <xs:attribute name="ReturnType" type="xs:string"/>
      <xs:attribute name="IsConstructor" type="xs:boolean" default="false"/>
      <xs:attribute name="DisplayData" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="ClassDataItemList">
    <xs:complexType>
      <xs:sequence minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="ClassDataItem">
          <xs:annotation>
            <xs:documentation>The List of Class Members</xs:documentation>
            <xs:appinfo source="ListType">ObservableCollection</xs:appinfo>
          </xs:annotation>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="Type" type="xs:string" use="required"/>
      <xs:attribute name="Name" type="xs:string" use="required"/>
      <xs:attribute name="Color" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Jedzia/BackBock/Jedzia.BackBock.Model/Data/ClassDataItemList.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- edited with XMLSpy v2011 rel. 2 (http://www.altova.com) by Venom (ICO) -->
<ClassDataItemList Type="Type1" Name="MyClass" Color="Color1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ClassDataItem.xsd">
  <ClassDataItem ItemType="Fields" Name="field1" ReturnType="string" Color="Color1" Scope="Scope1" AccessSpecifier="private" Static="true" Signature="Signature1" Parameternames="Parameternames1" IsConstructor="false" DisplayData="DisplayData1"/>
  <ClassDataItem ItemType="Fields" Name="myNumber" ReturnType="long" Color="Color1" Scope="Scope1" AccessSpecifier="private" Static="false" Signature="Signature1" Parameternames="Parameternames1" IsConstructor="false" DisplayData="DisplayData1"/>
  <ClassDataItem ItemType="Fields" Name="cnt" ReturnType="int" Color="Color1" Scope="Scope1" AccessSpecifier="public" Static="false" Signature="Signature1" Parameternames="Parameternames1" IsConstructor="false" DisplayData="DisplayData1"/>
  <ClassDataItem ItemType="Fields" Name="_substractor" ReturnType="byte" Color="Color1" Scope="Scope1" AccessSpecifier="private" Static="false" Signature="Signature1" Parameternames="Parameternames1" IsConstructor="false" DisplayData="DisplayData1"/>
  <ClassDataItem ItemType="Properties" Name="HasValue" ReturnType="bool" Color="Color3" Scope="Scope3" AccessSpecifier="private" Static="false" Signature="Signature3" Parameternames="Parameternames3" IsConstructor="false" DisplayData="DisplayData3"/>
  <ClassDataItem ItemType="Properties" Name="IsDingens" ReturnType="bool" Color="Color3" Scope="Scope3" AccessSpecifier="protected" Static="false" Signature="Signature3" Parameternames="Parameternames3" IsConstructor="false" DisplayData="DisplayData3"/>
  <ClassDataItem ItemType="Properties" Name="TargetName" ReturnType="string" Color="Color3" Scope="Scope3" AccessSpecifier="public" Static="false" Signature="Signature3" Parameternames="Parameternames3" IsConstructor="false" DisplayData="DisplayData3"/>
  <ClassDataItem ItemType="Methods" Name="Constructor" ReturnType="void" Color="Color2" Scope="Scope2" AccessSpecifier="public" Static="false" Signature="Signature2" Parameternames="Parameternames2" IsConstructor="true" DisplayData="DisplayData2"/>
  <ClassDataItem ItemType="Methods" Name="ToString()" ReturnType="string" Color="Color2" Scope="Scope2" AccessSpecifier="protected" Static="true" Signature="Signature2" Parameternames="Parameternames2" IsConstructor="false" DisplayData="DisplayData2"/>
  <ClassDataItem ItemType="Methods" Name="Remove()" ReturnType="void" Color="Color2" Scope="Scope2" AccessSpecifier="public" Static="false" Signature="Signature2" Parameternames="Parameternames2" IsConstructor="false" DisplayData="DisplayData2"/>
  <ClassDataItem ItemType="Methods" Name="Initialize()" ReturnType="void" Color="Color2" Scope="Scope2" AccessSpecifier="private" Static="false" Signature="Signature2" Parameternames="Parameternames2" IsConstructor="false" DisplayData="DisplayData2"/>
  <ClassDataItem ItemType="Events" Name="NotifyPropertyChanged" Color="Color3" Scope="Scope3" AccessSpecifier="public" Static="false" Signature="Signature3" Parameternames="Parameternames3" IsConstructor="false" DisplayData="DisplayData3"/>
  <ClassDataItem ItemType="Events" Name="MyEvent" Color="Color3" Scope="Scope3" AccessSpecifier="public" Static="false" Signature="Signature3" Parameternames="Parameternames3" IsConstructor="false" DisplayData="DisplayData3"/>
  <ClassDataItem ItemType="Events" Name="Clicked" Color="Color3" Scope="Scope3" AccessSpecifier="public" Static="false" Signature="Signature3" Parameternames="Parameternames3" IsConstructor="false" DisplayData="DisplayData3"/>
</ClassDataItemList>
